### ISSUE TITLE
error when creating a new map

### ISSUE THREAD

**Issue by tairea** [tairea/galaxy-maps-v2#103]
when create a new Galaxy Map, the GalaxyView page doesnt load any mapping tools/buttons.

![Image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/478a2b80-b374-496b-9101-b5f3964b36db)

it returns this error
`"FirebaseError: Course not found: 93DUArPM4JKYa83G0sES"` even though that courseId is in the database?

![Image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/9042a69f-22ea-4f61-8ecc-df14178785a0)

**Comment by charsleysa** [comment]
Fixed by #109 

@tairea @Ben-Tai can you double check to see that the issue is resolved for you?

**Comment by tairea** [comment]
yep, confirmed fixed with #109
