### ISSUE TITLE
Work submitted for Review.

### ISSUE THREAD

**Issue by scottsou145** [tairea/galaxy-maps-v2#77]
Separating Completed from work submitted so teachers can easily see what needs to be reviewed. The completed and review currently mixes and it can lead to things missed.

Maybe having a green box for completed just to separate completed from review.

**Comment by scottsou145** [comment]
![Image](https://github.com/tairea/galaxy-maps-v2/assets/147571499/cf569d6f-5b66-470f-8bb9-885bdc374bd0)

**Comment by tairea** [comment]
Gotcha. Sounds good

**Comment by tairea** [comment]
added two boxes below that will show completed help and submissions.
the boxes above will not show completed ones
this change is in PR #117 
![image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/58e9d54d-a01e-4cba-a48f-35e0bc1c7f11)
